#+title: Cities of Transistors
#+author: Elam Day-Friedland

* Meeting 12.2.25

*  notes
schematic as the pre-pictorial catastrophe

Stiegler- This exteriorization produces a new kind of time, because the temporal horizon of human experience includes not only biological memory but technical, recorded, machinic, repeatable memory.
- tertiary retention via exteriorized memory (technology)

  what does black-box prototyping/experimentation have to do with this

  the cliché is not merely inside painters’ heads; it is in the technological memory system of the entire culture.

  Bacon tries not to “paint the photograph,” because for him the photograph already captures the cliché.

  555 as an implementation of time as technics

  innovation in circuit design

The 555 is the perfect place to stage resistance:

- It’s simple enough to reverse-engineer or bias into weird modes

- It’s common enough that its clichés are deeply entrenched

- It’s stable enough that you can push it into strange attractors and chaotic behavior (catastrophe literally becomes part of the electrical dynamics)

how can you violate the schema of a 555? it has a very specific purpose

Kind of emergency room environment trying to debug blackbox 555 timer (with probes hooked onto legs), talk about the impossibility of introspection

how do cliches inhibit tinkering



electronics with ICs are maybe less ammenable to tinkering because of the more narrow acceptance criteria

has electrical engineering been terratorialized

a lot of things have to slot in to place for your experiment to be even reasonably interpretable

the tension between cliche (i.e. having something work) and experimentation
- feedback/recursion?
- maybe have some breadboard inviting tinkering and experimentation but restricted s.t. only the canonical setup of the 555 can be created
-
  what is the method that goes beyond representation?
  representation is a black box (even with the microct)- how can we show

installation of breadboard and screen with scope readout

* Gediminas meeting 10.4.25
references:
Christian marklei- the clock
William kendrich working with Peter galistron work on time and regret “the refusal of time”


Breadboard with scope and overlayed screen showing internal function
What is the method that goes beyond representation
Tensions between what is important and what sis discarded
Dialectical between positive and acknowledging what is discarded
Pile of parts with the wrong values
Project as a motherboard- what outputs can it create?
Outputs - electrical, map to sound, video
https://cyber.harvard.edu/events/what-intelligence-lessons-ai-about-evolution-computing-and-minds
Ask avi about scope and tools, garo Dolan technical folks

* Midterm feedback 10.30.25
AviGilad: M1 Chip — apple. very energy efficient
Tiny clock, infrastructure. Chip architecture. Entire world economy - city channels.
Tobias: be more specific. internet cables.
Hugh: MOMA has early patent drawings of chip designs. Think of ways in which recursively are reabsorbed into the city infrastructure. Chips —> being displayed as art in the moma. discursive, replicate city architecture..
Vladimir: to provoke you:
Ula: what can you drop in to illuminate these processes. Here they’re invisible in this map (the processes you’re talking about)
Whats the temporal behaviour? Score, catalyst
Tobias: idea of  a clock is super interesting. Functionality (Chip is simple). Clock that gives certain.. timestamp. Measurement with the chip, and measurement in the city. for the city, is there something you can juxtapose? equivalent pulsating behaviour..
Ula: layering and depth, flip the map (?)
Aram: cables, time, stock exchange. Nanoseconds..

** my notes
tobias- look at internet infra maps (fiber cables etc.)

chips as art (MOMA)

Gediminas- is this a graphic or graphic that represents operation

looking at collapsed representations and lifting htem back into dynamism

creating a ?? of information flow from some spore

financial cycles

* CANCELED transparent film paper of city on top of micrpgraph

- State "CANCELED"   from "TODO"       [2025-11-25 Tue 20:19] \\
  project went a different direction
* overview

This project seeks to explore common notions of structure,
movement,
and information between human-scale architecture and the microarchitecture of the integrated circuit nanostructures that pervade the modern world.


massively parallel processors that feed ever-growing demand for compute resources. Of particular interest are the following computational architectural motifs (that I think may have parallels in urban spaces): (potentially) a lack of verticality / a pervasive 'flatness',
highly regular/structured layout of standardized components (forming distinct regions at different levels of the hierarchy),
and hierarchical communication/movements channels.

I'm looking for input from an macro-architecture/urban planning perspective on motifs or concepts that could lend more formal structure to the "silicon cities" I'm interested in creating.

*  The city of transistors
infrastructure (power domains)
zoning (specialized processors)
transportation

difference: cities can change at a structural level in-place,
chips not so much (they are limited,
xfor the most part,
to the flexibility that was designed)


* GPU Background

A GPU (graphics processing unit) is a large array of small procesing units that perform operations in parallel.
The processing units communicate to synchronoize and share results,
but communication (moving information across the physical chip) is expensive (time, energy) compared to keeping it within the individual units so it is minimized.

Here are some characteristics of GPUs that may be fruitful to explore in relation to American suburbs:

* Lack of Verticality
In compute chips,
transistors are (for now) laid out in a single 2D layer.
This forces long interconnecting roads/busses that remain underutilized most of the time,
aside from communication phases when they're backed up.

* Highly Regular Layout
When all units are optimized to do ~the same thing (it's easier to organize a homogenous array of compute units than 100 specialized ones),
there is little space for uniqueness.

The demand for easy parallelism necessitates sprawling repition.

* Hierarchical Communication Channels
As a result of the sprawling 2D array of compute units,
hierarchical transportation channels (garage/cul-de-sac < local road < main road < highway) must exist.

Transportation channels may be hierarchical,
but everything is very regular + homogenous.

* working
We could define a 'suburban' processor architecture,
with architecture diagrams and rtl/layout?

Present along a darpa/nsf grant application

What parallels do we want to draw?
- economic motivation:
  certain resources (land/area) are cheaper than others (density)
- ease of design / 'programming'
homogenous fabric is nominally easier to reason about
- performance goals
  maximize throughput by minimizing communication
* Looking forward
how can urban design be influenced by architecture? / vice versa

urban architecture -> heterogenous, 3d architectures

there is no more budget for homogenous, 'easy' architectures in chip
